### ISSUE TITLE
Ast_traverse.ast_mapper_of_map replacement?

### ISSUE THREAD

**Issue by little-arhat** [janestreet/ppx_core#10]
Hi, 

I'm trying to update `ppx_fun` to `ppx_core v.0.9.0`, but couldn't find replacement for `Ast_traverse.ast_mapper_of_map`. I used to have `Ast_traverse.map` which was converted to `Ast_mapper` and registered — https://github.com/little-arhat/ppx_fun/blob/master/src/ppx_fun.ml#L133. Is it possible to do something like this in current `ppx_core` or I have to use some `ppx_driver` or remove `ppx_core` entirely? 

Thanks!

**Comment by diml** [comment]
Ah, indeed this was removed during the port to ocaml-migrate-parsetree. It could be re-added since now ocaml-migrate-parsetree captures Ast_mapper as well. Note that you only need to fill in the `structure` and `signature` fields of the mapper, so you can just use:

```ocaml
{ Ast_mapper.default_mapper with
  structure = fun _ -> map#structure
; signature = fun _ -> map#signature
}
```

BTW, you should also consider switching to the [ocaml-migrate-parsetree driver](https://github.com/let-def/ocaml-migrate-parsetree/blob/master/MANUAL.md#driver) and distribute your rewriter as a library. This is the way forward using ppx. Alternatively using ppx_driver is fine as well since it integrates with the omp driver.

**Comment by little-arhat** [comment]
That's what I've tried at first:

```
let ast_mapper_of_map (map : #map) : Ast_mapper.mapper =
  let open Ast_mapper in
  { default_mapper with
    expr = fun _ -> map#expression}
```

but:

```
This expression has type
         Ppx_core.Light.expression -> Ppx_core.Light.expression
       but an expression was expected of type
         Parsetree.expression -> Parsetree.expression
       Type Ppx_core.Light.expression = Ast_403.Parsetree.expression
       is not compatible with type Parsetree.expression
```

What is the correct way to convert version-specific parsetree to "current" parsetree? Is there documentation somewhere I miss? 

Thanks!

**Comment by diml** [comment]
There is just a quick mention of this [here](https://github.com/janestreet/ppx_core#ast-version). You can try this:

```ocaml
{ Ast_mapper.default_mapper with
  structure = fun _ -> Ppx_ast.Selected_ast.to_ocaml_mapper Structure map#structure
; signature = fun _ -> Ppx_ast.Selected_ast.to_ocaml_mapper Signature map#signature
}
```

**Comment by diml** [comment]
But really you should do this:

```ocaml
Migrate_parsetree.Driver.register ~name:"fun" (module Ppx_ast.Selected_ast)
  (fun _ _ ->
    { Ppx_ast.Selected_ast.Ast_mapper.default_mapper with
      structure = fun _ -> map#structure
    ; signature = fun _ -> map#signature
    })
```

**Comment by little-arhat** [comment]
@diml thanks, `Ppx_ast.Selected_ast.to_ocaml_mapper` is indeed what I was looking for (and I saw it, but couldn't figure how to use it %( ).

I did use `ppx_driver` in previous version, but than removed it (https://github.com/little-arhat/ppx_fun/commit/1d67ea83f4593a2092952cb162102a60427ac279) because the code was easier without it. I'll try `ppx_driver` again, thanks.

**Comment by diml** [comment]
Yh I guess sometimes it's easier to do things directly. Basically what ppx_driver gives you is robust checks and merging of all rewriters into a single pass with a clear semantic. These are things we care about at least for our critical code but it might not be that important in general and it only works if you use only ppx_driver based rewriters.

BTW the patch you showed me mostly fiddles with the build system, you should try jbuilder, it would simplify things a lot :)
