### ISSUE TITLE
Installation does not work with OASIS

### ISSUE THREAD

**Issue by jaapb** [janestreet/ppx_core#6]
When installing the package with OASIS alone (when packaging for pkgsrc, I like to avoid opam), I get error messages of the sort 'Cannot find file 'src/META' for findlib library ppx_core'.

This is a problem that exists with multiple Jane Street libraries (ppx_driver and ppx_type_conv seem to suffer from it as well), but I'm reporting it here (where I first encountered the problem) so it can be discussed centrally.

For ppx_core, the problem is mostly that the library is in src/ while the META file is in the main directory. The _oasis file expects the META file in src. I've currently solved this by moving META.ab to src and patching the _oasis file accordingly.
For ppx_driver, there is a larger problem in that there are several sub-libraries that need to be catered for (plus the problem of META needing to be in src), so it becomes necessary to add FindlibContainer lines to the _oasis file for all sub-libraries.

I'm happy to submit pull requests/patches with my solution if required, but before I do that I'd like to ask if you agree with the general idea of the solution or whether you'd like to solve it in another way.

**Comment by diml** [comment]
We used to rely on oasis to generate META files and we had all the relevant FindlibXXX fields inside our `_oasis` files. However, recently META files became overly complicated and oasis is no longer able to handle all the subtleties.

Given the way we publish our code it's a lot simpler for us to generate META files directly. I'm a bit surprised that you get these errors as `META` is no longer listed in the `Puglins:` field in our `_oasis` files. oasis shouldn't even care about it. Is this an error or just a warning?

**Comment by jaapb** [comment]
No, it's a proper error. I don't know oasis all that well, so perhaps there is 
a better way to deal with the fact that the META file is not in the same 
directory as the library itself - moving the file to the right directory does 
seem a little unelegant.

**Comment by diml** [comment]
At what point do you get this error though? I don't get this error locally

**Comment by jaapb** [comment]
When I run './setup -install'. This is with the latest version from github and 
oasis 0.4.6.

**Comment by diml** [comment]
Installation with oasis is no longer supported. We are now using opam-installer, you can look at the rule for `make install`
