### ISSUE TITLE
Broken with 4.04

### ISSUE THREAD

**Issue by vbmithr** [janestreet/ppx_core#8]
```
# File "src/code_matcher.ml", line 151, characters 13-30:
# Error: Unbound value Pprintast.default
```

**Comment by MiloDavis** [comment]
I'm getting the same error.

**Comment by diml** [comment]
What version of ppx_core are you trying to build? There is no more reference to `Pprintast.default` at the tip of the git repo

**Comment by MiloDavis** [comment]
I'm on OSX 10.11.6, building ppx_core 114.20+69 via Opam.  I'm using OCaml 4.04.0 and originally encountered this error when attempting to build Core, though attempting to install ppx_core on its own does not work either.

**Comment by MiloDavis** [comment]
If I run `opam update && opam upgrade` after running `opam switch` ppx_core installs without incident.

**Comment by diml** [comment]
Yeah that's expected, 4.04 is only supported since a few days
