### ISSUE TITLE
Broken with 4.03.0

### ISSUE THREAD

**Issue by vbmithr** [janestreet/ppx_core#9]
I have this issue:

```File unavailable: ppx_core.install``` (edited)

I also have the same issue with `sexplib` and `typerep`, both on 4.03.0.

**Comment by diml** [comment]
Do you mean `ppx_core.install`?

**Comment by vbmithr** [comment]
Yep. Sorry.

**Comment by diml** [comment]
What version of jbuilder and ppx_core do you have?

**Comment by vbmithr** [comment]
On 23/12/2016 13:24, Jérémie Dimino wrote:
> What version of jbuilder and ppx_core do you have?

Both 114.20+69

**Comment by diml** [comment]
What's the output of `jbuilder -drules ppx_core.install`?

**Comment by vbmithr** [comment]
On 23/12/2016 14:57, Jérémie Dimino wrote:
> What's the output of |jbuilder -drules ppx_core.install|?

I can install those packages when pinning them. Seems an OPAM problem (I'm using
opam2).

Upstream bug report: https://github.com/ocaml/opam/issues/2799

**Comment by hhugo** [comment]
Closing as ppx_core does not support OCaml 4.03 anymore.
